### ISSUE TITLE
Feedback Quiz Lv.4 Form

### ISSUE THREAD

**Issue by udiiin** [filbertreinaldha/sandboxhsi-nextjs-level4-form#1]
Halo Mas @filbertreinaldha, terima kasih untuk submissionnya.  
Saya ada beberapa feedback:

**1.)**  
Componentnya terlalu besar mas, baiknya dipisah2 lagi biar lebih mudah dibaca.

**2.)**  
Opsimisasi createStyles:  
Code spt ini `const x = createStyles((theme) => ({ ... }).classes` tidak bergantung pada state dari sebuah component.  
Sehingga akan lebih baik jika dipanggil di luar component saja.

Before:

```
const Comp = () => {
  const x = createStyles((theme) => ({ ... }).classes
  return <></>
}
```

After:

```
const x = createStyles((theme) => ({ ... }).classes

const Comp = () => {
  return <></>
}
```

**3.)**  
Sebenarnya tidak perlu membuat state lagi secara manual (`useReducer`) untuk menyimpan value2 dari yg diinput user. Karena di sini sudah menggunakan react-hook-form. Keseluruhan value sudah cukup disimpan melalui `useForm`.

**4.)**  
💡 Bisa manfaatkan `register`: `<input {...register("nama_field")} />`

**5.)**  
Namin convention: untuk penamaan fungsi, baiknya menggunakan _verb_ (kata kerja).  
`nextStep` → `goToNextStep`,  
`prevStep` → `goToPrevStep`

.

Semoga dimudahkan, barokallaahu fiik...

**Comment by filbertreinaldha** [comment]
Halo mas @udiiin
Alhamdulillah, syukron atas waktu dan effort untuk memberikan feedback-nya. Sudah saya update ya. Berikut beberapa tanggapan poin-poin feedback mas Afif:
1. Iya mas hehe, sudah saya pecah-pecah jadi beberapa component, semoga jadi lebih enak dibaca.
2. createStyles sudah saya pisahkan ke file sendiri. Sebelumnya sudah saya coba tapi selalu ada salah di import dan cara pemanggilan. Alhamdulillah kali ini sudah bisa.
3. Di quiz kali ini saya coba pakai Stepper dari Mantine mas, dan Stepper ini 11-12 dengan model Tab. Jadi kurang lebih component di dalam-nya mengalami unmount-mount ketika berpindah page. Nah, di [FAQ](https://www.react-hook-form.com/faqs/#Howtoworkwithmodalortabforms)-nya RHF di-state bahwa form state bisa hilang akibat component yang unmount-mount, sehingga mereka menyarankan untuk menyimpan form value di sebuah state global. Saya juga sudah mencoba menggunakan form state bawaan RHF, tapi ya begitu, ada value-value yang hilang / tertimpa ketika berpindah page (terutama halaman Services & Budget yang sama-sama Radio). Akhirnya saya tetap pakai reducer seperti di Level 2.
4. Di quiz kali ini saya pun menggunakan custom input dari Mantine. Setelah saya baca2 di [docs](https://react-hook-form.com/docs/usecontroller/controller) RHF, untuk custom Input disarankan pakai Controller dari RHF sebagai wrapper dan function register tidak perlu dipanggil lagi karena sudah di-handle oleh Controller.
5. Siap, updated untuk naming function prevStep & nextStep.

Sekian mas, mohon bantuan dicek lagi dan tambahan feedback-nya...

**Comment by udiiin** [comment]
Oke utk yg pakai controller gak masalah.. 👌 

Utk yg penggunaan `useReducer`, saya udah cobain tanpa `useReducer` dan baik2 saja mas, valuenya gak hilang/tertimpa.

**Comment by filbertreinaldha** [comment]
Wah, saya coba juga bisa mas sekarang, alhamdulillah! Apa gara2 udah dipecah jadi component-component ya? Pas file index.tsx masih panjang soalnya gabisa hehehe. Done updated di latest push ya mas.

**Comment by udiiin** [comment]
Sipp mas, udah mantab 👍
